### ISSUE TITLE
Merchant Token

### ISSUE THREAD

**Issue by wassimk** [payeezy/payeezy#1]
When making token transaction requests the API wants the merchant token in the header and a token in the payload. It's really confusing since both are called token. The merchant tokens should be more clearly identified as the merchant specific token.

**Comment by nohup-atulparmar** [comment]
Merchant token is required for Merchant authentication.this is unique for each merchant.
where are payment token is valid for each transaction. for example if customer purchase 'home goods' for $50 and wants to return $10. then transaction token is valid for "Purchase-Refund". Transaction token is valid for limited period of time(~ 15 min). Please let me know if you need more clarification.

**Comment by wassimk** [comment]
Thanks for the clarification. In the Ruby implementation it calls both of them token. I think it would be better to rename the merchant token variables. It kind of threw me for a little bit when testing.

**Comment by nohup-atulparmar** [comment]
Thanks for the feedback. We will rename variables and place under https://github.com/payeezy/payeezy_ruby along with documentation.
