### ISSUE TITLE
Java unit tests are not working 

### ISSUE THREAD

**Issue by MssRajat** [payeezy/payeezy#2]
Java unit tests are not working  >>
 I am trying to run the junit test from the  supplied code  . But it does n't work . 
I am getting test failure and 400 response 
any suggestion is highly appreciated .

**Comment by nohup-atulparmar** [comment]
Hi Rajat, Please use correct apikey/merchant token/Secret key and rerun the test.

**Comment by githubmss** [comment]
Hello , even after replacing the Merchant Token/Secret Key/Api Key i am getting same issue (See Below)
08 Apr 2015 17:01:09 DEBUG DefaultClientConnection - Receiving response: HTTP/1.1 400 Bad Request
08 Apr 2015 17:01:09 DEBUG headers - << HTTP/1.1 400 Bad Request
Thanks.

**Comment by nohup-atulparmar** [comment]
can you please provide the payload/JSON request ?
