### ISSUE TITLE
build - install [invalid syntax]

### ISSUE THREAD

**Issue by lemmetry** [payeezy/payeezy#4]
> ~/payeezy/payeezy_direct_API-master/payeezy_python/example$ python setup.py build
> running build
> running build_py
> ~/payeezy/payeezy_direct_API-master/payeezy_python/example$ sudo python setup.py install
> running install
> running build
> running build_py
> running install_lib
> creating /usr/local/lib/python2.7/dist-packages/payeezy
> copying build/lib.linux-x86_64-2.7/payeezy/**init**.py -> /usr/local/lib/python2.7/dist-packages/payeezy
> copying build/lib.linux-x86_64-2.7/payeezy/api_methods.py -> /usr/local/lib/python2.7/dist-packages/payeezy
> copying build/lib.linux-x86_64-2.7/payeezy/http_authorization.py -> /usr/local/lib/python2.7/dist-packages/payeezy
> byte-compiling /usr/local/lib/python2.7/dist-packages/payeezy/**init**.py to **init**.pyc
> byte-compiling /usr/local/lib/python2.7/dist-packages/payeezy/api_methods.py to api_methods.pyc
>   File "/usr/local/lib/python2.7/dist-packages/payeezy/api_methods.py", line 73
>     valuelink:
>              ^
> SyntaxError: invalid syntax
> byte-compiling /usr/local/lib/python2.7/dist-packages/payeezy/http_authorization.py to http_authorization.pyc
> running install_egg_info
> Writing /usr/local/lib/python2.7/dist-packages/payeezy-1.0.egg-info

**Comment by nohup-atulparmar** [comment]
Please use https://github.com/payeezy/payeezy_direct_API/tree/master/payeezy_python
