### ISSUE TITLE
EPOCH UTC Time ...

### ISSUE THREAD

**Issue by rjhaz** [payeezy/payeezy#5]
Well, I am guessing I am the only person that is trying to use the PHP API (Payeezy.php) that also sets his PHP timezone to my local timezone. I could not figure out why I was ALWAYS getting a HMAC error... I looked at the code and found that it is using, around line 600, 
    $timestamp = strval(time()_1000); //time stamp in milli seconds 
INSTEAD OF:
    $timestamp = strval((time() - date('Z'))_1000); //time stamp in milli seconds – MAKE SURE YOU ARE UTC based - always. 

So the 'EPOCH UTC' time was always off...  

So,, I am posting this in hopes someone else is saved a little time... 

Ray

**Comment by nohup-atulparmar** [comment]
Thanks Ray
